- hosts: all
  become: yes
  remote_user: ubuntu
  taskes:
    - name: "update apt cache"
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian" 

    - name: "update yum cache"
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat" 

    - name: "install nginx on ubuntu"
      apt:
        name: ['nginx', 'nginx-common']
        state: present
      when: ansible_os_family == "Debian" 

    - name: "install nginx on ubuntu"
      yum:
        name: ['nginx']
        state: present
      when: ansible_os_family == "RedHat" 

    - name: "enable nginx service"
      service:
        name: nginx
        state: restarted
        enable: yes
      when: ansible_os_family == "RedHat" 