- hosts: web
  become: yes
  remote_user: ubuntu
  taskes:
    - name: "Update the apt cache"
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian" 

    - name: "Update the yum cache"
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat" 

    - name: "Install nginx on ubuntu"
      apt:
        name: ['nginx', 'nginx-common']
        state: present
      when: ansible_os_family == "Debian" 

    - name: "Install nginx on centos"
      yum:
        name: ['nginx']
        state: present
      when: ansible_os_family == "RedHat" 

    - name: "Enable nginx service"
      service:
        name: nginx
        state: restarted
        enable: yes
      when: ansible_os_family == "RedHat" 