version: 2.1

jobs:
  configure_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file ec2.yml \
              --stack-name web \
              --region us-east-1

      - run:
          name: make inventory file
          command: |
            yum install -y tar gzip
            echo "[web]" > inventory.txt 
            echo "hello" >> inventory.txt

  server_configuration: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout    
      - attach_workspace:
          at: .
      - run:
          name: reading inventory file
          command: |
            cat inventory.txt

      #- add_ssh_keys:
      #   fingerprints: ["0c:55:f7:d7:ad:e3:73:19:0b:e6:c6:46:5c:04:76:94"] # You can get this ID in the section where you registered the SSH Key
      #- run:
      #    name: Install dependencies
      #    command: |
      #      # install the dependencies needed for your playbook
      #      apk add --update ansible 
      #- run:
      #    name: Configure server
      #    command: |
      #      ansible-playbook -i inventory.txt main4.yml


workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - configure_infrastructure
